spring:
  application:
    name: instagram

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  
    



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

myapp:
  instagram:
    cookie:
      access-token:
        expiration-time: 404800000
      refresh-token:
        expiration-time: 604800000

    jwt:
      access-token:
        secretkey: "3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b"
        expiration-time: 120000

      refresh-token:
        secretkey: "3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b"
        expiration-time: 604800000
